version: "3.8"
services:
  nginx:
    image: nginx:1.19.5
    container_name: nginx
    networks:
      - network
    volumes:
      - /home/django_course/nginx.conf:/etc/nginx/nginx.conf
      - static:/data/static
      - media:/data/media
    ports:
      - 80:80
    deploy:
      labels:
        - "com.docker.stack.namespace="
  django_container_gunicorn:
    image: django_image_gunicorn:1
    container_name: django_container_gunicorn
    networks:
      - network
    volumes:
      - static:/home/My-Home/staticfiles
      - media:/home/My-Home/media
    deploy:
      labels:
        - "com.docker.stack.namespace="
    secrets:
      - DJANGO_SECRET_KEY
      - MARIADB_PASSWORD
  mariadb:
    image: mariadb:10.5
    container_name: mariadb
    networks:
      - network
    volumes:
      - database:/var/lib/mysql
    ports:
      - 3306:3306
    secrets:
      - MARIADB_ROOT_PASSWORD
      - MARIADB_PASSWORD
    command: --bind-address=0.0.0.0
    environment:
      MARIADB_DATABASE: django_homepage
      MARIADB_USER: jake
      MARIADB_ROOT_PASSWORD_FILE: /run/secrets/MARIADB_ROOT_PASSWORD
      MARIADB_PASSWORD_FILE: /run/secrets/MARIADB_PASSWORD
    deploy:
      labels:
        - "com.docker.stack.namespace="

networks:
  network:

volumes:
  static:
  media:
  database:

secrets:
  DJANGO_SECRET_KEY:
    external: true
  MARIADB_ROOT_PASSWORD:
    external: true
  MARIADB_PASSWORD:
    external: true









